remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"
title: About me
description: Here you can find some of my work and achievements. Enjoy!

plugins:
  - jekyll-include-cache

